# Generated by Django 5.1.7 on 2025-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
