# Generated by Django 5.1.7 on 2025-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_user_device_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('blind', 'Blind'), ('admin', 'Admin')], default='Volunteer', max_length=50),
        ),
    ]
