# Generated by Django 5.1.7 on 2025-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_fcm_token',
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expo_notification_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
